### ISSUE TITLE
Error with questions

### ISSUE THREAD

**Issue by seangrogg** [talentgg/talentgg#82]
When answering a question, the question text never changes (though the radio buttons do). There's also a console error that pops up. Worth looking into.

**Comment by jonathanseneris** [comment]
is this still an open issue? if so, how do i recreate it?

**Comment by seangrogg** [comment]
No, sorry, meant to move this to resolved. I had the issue and I think it came down to an error somewhere on my part that resolved itself at some point. Closing.
